FROM node:16.14.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install serve -g --silent
COPY . ./

ARG HOST_ENV
ARG VERSION
ARG REMOTE_FALCON_GATEWAY
ARG DATADOG_CLIENT_TOKEN
ARG VIEWER_JWT_KEY
ARG GOOGLE_MAPS_KEY
ARG PUBLIC_POSTHOG_KEY

RUN echo "HOST_ENV $HOST_ENV"
RUN echo "VERSION $VERSION"

ENV REACT_APP_HOST_ENV=$HOST_ENV
ENV REACT_APP_VERSION=$VERSION
ENV REACT_APP_REMOTE_FALCON_GATEWAY=$REMOTE_FALCON_GATEWAY
ENV REACT_APP_DATADOG_CLIENT_TOKEN=$DATADOG_CLIENT_TOKEN
ENV REACT_APP_VIEWER_JWT_KEY=$VIEWER_JWT_KEY
ENV REACT_APP_GOOGLE_MAPS_KEY=$GOOGLE_MAPS_KEY
ENV REACT_APP_PUBLIC_POSTHOG_KEY=$PUBLIC_POSTHOG_KEY

RUN npm run build

# start the nginx web server
CMD ["serve", "-s", "/app/build"]